export const SET_USERS = 'SET_USERS';
export const FETCH_USERS_FAILED = 'FETCH_USERS_FAILED';
export const SEARCH_USERS = 'SEARCH_USERS';
export const SET_USER_ID = 'SET_USER_ID';
export const RESET_USER = 'RESET_USER';
export const SET_SINGLE_USER = 'SET_SINGLE_USER';
export const FETCH_SINGLE_USER_FAILED = 'FETCH_SINGLE_USER_FAILED';

export const SET_REPOS = 'SET_REPOS';
export const FETCH_REPOS_FAILED = 'FETCH_REPOS_FAILED';
export const SET_SINGLE_REPO = 'SET_SINGLE_REPO';
export const FETCH_SINGLE_REPO_FAILED = 'FETCH_SINGLE_REPO_FAILED';
export const SET_SINGLE_REPO_ID = 'SET_SINGLE_REPO_ID';